name: login_screen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3
  razorpay_flutter: ^1.3.3
  http: ^1.2.1
  fluttertoast: ^8.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/

